# Generated by Django 2.1.7 on 2019-03-01 16:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('android_apps', '0001_initial'),
        ('android_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidAppReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date', models.DateTimeField(auto_now=True)),
                ('android_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='android_apps.AndroidApp')),
                ('android_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='android_users.AndroidUser')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='androidappreview',
            unique_together={('android_user', 'android_app')},
        ),
    ]
