# Generated by Django 2.1.7 on 2019-03-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_gamer_id', models.CharField(max_length=256, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('date_last_connected', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
