# Generated by Django 2.1.3 on 2018-11-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('dev_id', models.CharField(max_length=128)),
                ('category', models.CharField(blank=True, max_length=128, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=128, null=True)),
                ('short_description', models.CharField(blank=True, max_length=256, null=True)),
                ('long_description', models.TextField(blank=True, max_length=5000, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=256, null=True)),
                ('screenshots', models.CharField(blank=True, max_length=1200, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('reviews', models.IntegerField(blank=True, null=True)),
                ('installs', models.CharField(blank=True, max_length=64, null=True)),
                ('maturity', models.CharField(blank=True, max_length=64, null=True)),
                ('size', models.CharField(blank=True, max_length=64, null=True)),
                ('is_free', models.BooleanField(blank=True, null=True)),
                ('display_price', models.CharField(blank=True, max_length=64, null=True)),
                ('full_price', models.CharField(blank=True, max_length=64, null=True)),
                ('has_ads', models.BooleanField(blank=True, null=True)),
                ('has_iaps', models.BooleanField(blank=True, null=True)),
                ('current_version', models.CharField(blank=True, max_length=64, null=True)),
                ('android_version', models.CharField(blank=True, max_length=64, null=True)),
                ('last_updated', models.CharField(blank=True, max_length=64, null=True)),
                ('last_fetched', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-reviews'],
            },
        ),
    ]
